## ADMIN USERNAME
postgres

## SHOW DATABASES
\l

## SHOW TABLES
\dt+

## CREATE USER
CREATE USER $USER WITH PASSWORD '$PASSWORD' CREATEDB;

## CREATE DATABASE
CREATE DATABASE $DATABASE;

## GRANT USER ACCESS TO DATABASE
GRANT ALL PRIVILEGES ON DATABASE ${DATABASE} TO ${USER};

## SHOW DATABASES
SELECT datname FROM pg_database;