## SEARCH ALL TABLES FOR STRING

UPDATE ${TABLE} SET ${COLUMN_NAME} = replace(${COLUMN_NAME}, '${OLD_STRING}', '${NEW_STRING}');

## DELETE DATABASE

DROP DATABASE ${DATABASE_NAME};

## SEARCH AND REPLACE STRING IN .SQL EXPORT FILE

perl -pi -e 's/${OLD_TEXT}/${NEW_TEXT}/g' ${FILE_NAME}
perl -pi -e 's/${OLD_TEXT}/${NEW_TEXT}/g' * ## SEARCH AND REPLACE ALL FILES IN CURRENT FOLDER
